// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basicpb/message.proto

package basicpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BizConfig struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string               `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Value                string               `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BizConfig) Reset()         { *m = BizConfig{} }
func (m *BizConfig) String() string { return proto.CompactTextString(m) }
func (*BizConfig) ProtoMessage()    {}
func (*BizConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3e03da97df9150, []int{0}
}

func (m *BizConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizConfig.Unmarshal(m, b)
}
func (m *BizConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizConfig.Marshal(b, m, deterministic)
}
func (m *BizConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizConfig.Merge(m, src)
}
func (m *BizConfig) XXX_Size() int {
	return xxx_messageInfo_BizConfig.Size(m)
}
func (m *BizConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BizConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BizConfig proto.InternalMessageInfo

func (m *BizConfig) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BizConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BizConfig) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *BizConfig) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

type BizConfigResult struct {
	Bizconf              *BizConfig `protobuf:"bytes,1,opt,name=bizconf,proto3" json:"bizconf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BizConfigResult) Reset()         { *m = BizConfigResult{} }
func (m *BizConfigResult) String() string { return proto.CompactTextString(m) }
func (*BizConfigResult) ProtoMessage()    {}
func (*BizConfigResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3e03da97df9150, []int{1}
}

func (m *BizConfigResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizConfigResult.Unmarshal(m, b)
}
func (m *BizConfigResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizConfigResult.Marshal(b, m, deterministic)
}
func (m *BizConfigResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizConfigResult.Merge(m, src)
}
func (m *BizConfigResult) XXX_Size() int {
	return xxx_messageInfo_BizConfigResult.Size(m)
}
func (m *BizConfigResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BizConfigResult.DiscardUnknown(m)
}

var xxx_messageInfo_BizConfigResult proto.InternalMessageInfo

func (m *BizConfigResult) GetBizconf() *BizConfig {
	if m != nil {
		return m.Bizconf
	}
	return nil
}

func init() {
	proto.RegisterType((*BizConfig)(nil), "basic.BizConfig")
	proto.RegisterType((*BizConfigResult)(nil), "basic.BizConfigResult")
}

func init() { proto.RegisterFile("basicpb/message.proto", fileDescriptor_da3e03da97df9150) }

var fileDescriptor_da3e03da97df9150 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4e, 0xf3, 0x30,
	0x10, 0x84, 0x95, 0xf6, 0xcf, 0x0f, 0x75, 0x24, 0xa8, 0x2c, 0x90, 0xa2, 0x5e, 0x88, 0x7a, 0x8a,
	0x90, 0x6a, 0x4b, 0xe5, 0x0a, 0x07, 0xda, 0x37, 0x88, 0x7a, 0xe2, 0x66, 0x27, 0x1b, 0xb3, 0x10,
	0xdb, 0x51, 0xec, 0xa4, 0xd0, 0x1b, 0x6f, 0x8e, 0x70, 0x08, 0x70, 0xdb, 0x19, 0x7d, 0xd2, 0xcc,
	0x0e, 0xb9, 0x96, 0xc2, 0x61, 0xd9, 0x4a, 0xae, 0xc1, 0x39, 0xa1, 0x80, 0xb5, 0x9d, 0xf5, 0x96,
	0xc6, 0xc1, 0x5e, 0xdd, 0x28, 0x6b, 0x55, 0x03, 0x3c, 0x98, 0xb2, 0xaf, 0xb9, 0x47, 0x0d, 0xce,
	0x0b, 0xdd, 0x8e, 0xdc, 0xfa, 0x23, 0x22, 0x8b, 0x1d, 0x9e, 0xf6, 0xd6, 0xd4, 0xa8, 0xe8, 0x05,
	0x99, 0x61, 0x95, 0x46, 0x59, 0x94, 0xcf, 0x8b, 0x19, 0x56, 0x74, 0x49, 0xe6, 0xaf, 0xf0, 0x9e,
	0xc6, 0x59, 0x94, 0x2f, 0x8a, 0xaf, 0x93, 0x5e, 0x91, 0x78, 0x10, 0x4d, 0x0f, 0xe9, 0x79, 0xf0,
	0x46, 0x41, 0xef, 0x49, 0x52, 0x76, 0x20, 0x3c, 0x54, 0x07, 0xd4, 0x90, 0xfe, 0xcb, 0xa2, 0x3c,
	0xd9, 0xae, 0xd8, 0x18, 0xce, 0xa6, 0x70, 0x76, 0x98, 0xc2, 0x8b, 0xbf, 0xf8, 0xfa, 0x81, 0x5c,
	0xfe, 0x54, 0x28, 0xc0, 0xf5, 0x8d, 0xa7, 0xb7, 0xe4, 0x4c, 0xe2, 0xa9, 0xb4, 0xa6, 0x0e, 0x6d,
	0x92, 0xed, 0x92, 0x85, 0x87, 0xd8, 0x2f, 0x38, 0x01, 0xbb, 0xfd, 0xd3, 0x63, 0x05, 0xc3, 0x46,
	0xa1, 0x6f, 0x84, 0x64, 0x47, 0x61, 0xde, 0xd0, 0xa8, 0xce, 0x1e, 0xfd, 0x33, 0x2b, 0xad, 0xe6,
	0x2f, 0x28, 0x0c, 0x6b, 0xb0, 0xe7, 0x0e, 0xba, 0x01, 0x4b, 0xd8, 0x84, 0x3a, 0x6e, 0x9c, 0x84,
	0x7f, 0xaf, 0x27, 0xff, 0x07, 0x79, 0xf7, 0x19, 0x00, 0x00, 0xff, 0xff, 0x78, 0x1f, 0x09, 0x14,
	0x4f, 0x01, 0x00, 0x00,
}
